name: Pizza Delivery
on: [push,workflow_dispatch]

jobs: 
    Order-online:
        runs-on: macos-latest
        steps:
            - name: Open Mobile
              run: echo "Open Mobile"

            - name : Explore food
              run : echo "I want ot eat Pizza"

            - name : Payment
              run : echo "Payment done"
